version: '3.9'

secrets:
  db_user_passwd:
    file: ./db_user_passwd
  database_url:
    file: ./database_url
  jwt_secret:
    file: ./jwt_secret


services:
  postgres-db:
    image: postgres:17-alpine3.22
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: /run/secrets/db_user_passwd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_user_passwd
    networks:
      - cfgsycapi_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-app:
    image: marioramos0/cfgsvg4:2.0
    build: .
    deploy:
      replicas: 3
    ports:
      - "${PORT}:8000"
    secrets:
      - jwt_secret
      - database_url
    environment:
      DEBUG: 'True'
      ENV: 'development'
      PORT: ${PORT:-8000}
      DATABASE_URL: /run/secrets/database_url
      JWT_SECRET: /run/secrets/jwt_secret

    networks:
      - cfgsycapi_net


volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfssrv01,rw
      device: ":/data/docker-vols/group04/postgres_data"

networks:
  cfgsycapi_net:
    driver: overlay